### ISSUE TITLE
Buildroot Environment Setup for Client

### ISSUE THREAD

**Issue by hwsingh27** [cu-ecen-aeld/final-project-hwsingh27#1]
**DoD:**

- [x] Booting Raspberry Pi 3 B+ with Buildroot (Client-side).
- [x] Testing of sensors MLX90614 and DHT11.

**Tasks:**

- [x] Building basic buildroot image for RPi.
- [x] Adding SSH and Wi-Fi support
- [x] Testing both the sensors (MLX90614 and DHT11) on the Arduino UNO board to check if they work perfectly without any hardware fault.

**Blockers:**

- [x] Obtaining components - SD Card, HDMI cable, and Ethernet cable.
- [x] Booting issue while typing the password "root".

**Comment by hwsingh27** [comment]
**Blocker:** I loaded the image on my SD Card and booted my Raspberry Pi 3 B+, while logging I entered the password as "root". But when I press enter, it takes "r" at the end due to which I am unable to login into my RPi.

![20220328_152412](https://user-images.githubusercontent.com/62118804/160911814-c70d0bd9-431a-4ad8-a31a-823ca2559e7d.jpg)

**Comment by hwsingh27** [comment]
**Blocker Resolved:** Above mentioned booting issue was resolved by disabling the getty login option in `make menuconfig`, able to successfully login into RPi. 

Buildroot and SSH was setup successfully.
Wi-Fi was configured and verified by remote login using the command `ssh root@10.0.0.102`
Task-1 and Task-2 completed.

Issue completed in commit 77bdb8d8fdb985d095a71d354a832bb4cec4dd37

![IMG-9771](https://user-images.githubusercontent.com/62118804/161403413-6821e6f7-2bba-41c3-b85f-13a585d1eb18.jpg)

**Comment by hwsingh27** [comment]
Successfully tested the MLX90614 (temperature) sensor on the Arduino UNO.

![Screenshot (130)](https://user-images.githubusercontent.com/62118804/161444930-9694672c-1e5d-40f8-a5c0-b4d83f7e502b.png)

Hardware Setup for MLX90614.

![MLX90614](https://user-images.githubusercontent.com/62118804/161445541-18e9a9dd-42f0-4515-9cce-1c746e499c00.jpg)

**Comment by hwsingh27** [comment]
Successfully tested the DHT11 (humidity) sensor on the Arduino UNO board.

![Screenshot (129)](https://user-images.githubusercontent.com/62118804/161445078-c0c133a5-9bc3-474d-be53-61ab6eb77e0d.png)

Hardware Setup for DHT11.

![DHT11](https://user-images.githubusercontent.com/62118804/161445572-c8c7df46-ebcb-45ee-95e3-f0cc413dce15.jpg)

Task-3 Completed
