### ISSUE TITLE
Interfacing MLX90614 temperature sensor over I2C protocol

### ISSUE THREAD

**Issue by hwsingh27** [cu-ecen-aeld/final-project-hwsingh27#2]
**DoD:**

- [x] Interfacing the temperature sensor with Raspberry Pi 3 B+ to read the value of temperature from the sensor.
- [x] Communication between server and client through socket programming.

**Tasks:**

- [x] A user-space I2C driver that reads from and writes to the temperature sensor (using C programming).
- [x] Establish the connection between server and client by writing the client program (on PC).
- [x] Establish the connection between server and client by writing the client program (on Raspberry Pi 3 B+).

**Blockers:**

No blockers.

**Comment by hwsingh27** [comment]
Setup the hardware by interfacing the MLX90614 temperature sensor with Raspberry Pi 3 B+

![IMG_9862](https://user-images.githubusercontent.com/62118804/162641176-cc3fe750-8b66-4e80-a14e-f938b5d9ca0b.jpg)

**Comment by hwsingh27** [comment]
Verified if the i2c bus can detect the temperature sensor module using the command `i2cdetect -y 1`.

![Screenshot from 2022-04-10 15-25-29](https://user-images.githubusercontent.com/62118804/162641341-35674022-99c7-4541-a989-6897703437ad.png)

**Comment by hwsingh27** [comment]
Temperature in Celsius was fetched from the MLX90614 sensor module and displayed on the serial monitor at an interval of 1 second.
[Commit ID](https://github.com/cu-ecen-aeld/darshitagrawal_hwsingh27_shared/commit/08b28dff19781039e1aff0041ba18b976d33ab33)

![Screenshot from 2022-04-10 15-26-18](https://user-images.githubusercontent.com/62118804/162641682-eb314f5a-b189-4d48-b5a3-7eae19403a09.png)

**Comment by hwsingh27** [comment]
Wrote the client program to establish the connection between server and client by putting the loopback address using `ifconfig` command (on PC).
[Commit ID](https://github.com/cu-ecen-aeld/darshitagrawal_hwsingh27_shared/commit/08b28dff19781039e1aff0041ba18b976d33ab33)

![162358321-b118dce8-c3ed-4204-aa03-b530ad347088](https://user-images.githubusercontent.com/62118804/162641812-55d3ab42-bc8f-4459-8cd8-d06cedd49899.jpg)

**Comment by hwsingh27** [comment]
Modified the client program and loaded the image in both Raspberry Pi 3 B+ boards to establish the connection between the two boards to make them work as server and client to transmit the data bidirectionally.
[Commit ID](https://github.com/cu-ecen-aeld/darshitagrawal_hwsingh27_shared/commit/08b28dff19781039e1aff0041ba18b976d33ab33)

![162384937-1a6de5a1-3aa3-4bfb-a699-610f89ad068a](https://user-images.githubusercontent.com/62118804/162642020-b1e9f571-14fe-4675-82dc-fcbb3fd545c2.jpg)
